In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../../DataSets/emp.csv")
df

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10

In [7]:
df2 = df.copy()

In [8]:
df.columns

Index(['empno', 'ename', 'job', 'mgr', 'hiredate', 'sal', 'comm', 'deptno'], dtype='str')

In [9]:
sorted(df2["job"].unique())

['ANALYST', 'CLERK', 'MANAGER', 'PRESIDENT', 'SALESMAN']

In [10]:
df2["job"].value_counts()

job
SALESMAN     4
CLERK        4
MANAGER      3
ANALYST      2
PRESIDENT    1
Name: count, dtype: int64

In [11]:
cols_nums = {"job": {"ANALYST": 3, "CLERK": 5, "MANAGER": 2, "PRESIDENT": 1, "SALESMAN": 4}}

In [12]:
df2 = df2.replace(cols_nums)

In [13]:
df2.head()

   empno   ename job     mgr    hiredate   sal    comm  deptno
0   7839    KING   1     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE   2  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK   2  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES   2  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN   4  7698.0  09/28/2001  1250  1400.0      30

In [14]:
def salCatg(salary):
    if salary >= 3000:
        r = 1
    elif salary >= 1500:
        r = 2
    else:
        r = 3
    return r

In [15]:
df2["sal"] = df2["sal"].apply(salCatg)
df2.head()

   empno   ename job     mgr    hiredate  sal    comm  deptno
0   7839    KING   1     NaN  11/17/2001    1     NaN      10
1   7698   BLAKE   2  7839.0  05/01/2001    2     NaN      30
2   7782   CLARK   2  7839.0  06/09/2001    2     NaN      10
3   7566   JONES   2  7839.0  04/02/2001    2     NaN      20
4   7654  MARTIN   4  7698.0  09/28/2001    3  1400.0      30

In [16]:
df3 = df[df.columns]
df3.dtypes

empno         int64
ename           str
job             str
mgr         float64
hiredate        str
sal           int64
comm        float64
deptno        int64
dtype: object

In [17]:
df3["job"] = df3["job"].astype("category")
df3.dtypes

empno          int64
ename            str
job         category
mgr          float64
hiredate         str
sal            int64
comm         float64
deptno         int64
dtype: object

In [18]:
sorted(df3["job"].unique())

['ANALYST', 'CLERK', 'MANAGER', 'PRESIDENT', 'SALESMAN']

In [19]:
df3["job1"] = df3["job"].cat.codes
df3.head(len(df3))

    empno   ename        job     mgr    hiredate   sal    comm  deptno  job1
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10     3
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30     2
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10     2
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20     2
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30     4
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30     4
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30     4
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30     1
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30     4
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20     0
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20     1
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20     0
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20     1
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10     1

In [20]:
df3["comm1"] = df3["comm"].astype("category")
df3.dtypes

empno          int64
ename            str
job         category
mgr          float64
hiredate         str
sal            int64
comm         float64
deptno         int64
job1            int8
comm1       category
dtype: object

In [23]:
df3["comm1"] = df3["comm1"].cat.codes
df3.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,job1,comm1
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,3,-1
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,2,-1
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,2,-1
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,2,-1
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,4,3