In [2]:
import pandas as pd
import sklearn as skl
import matplotlib as mt
import numpy as np

In [3]:
df = pd.read_csv("./PlayGolf-MissingData.csv")

In [4]:
df.describe()

,Unnamed: 0,Weekday,Holiday,Temp,Humidity,Wind,Crowdedness
count,20.00000,20.000000,18.000000,16.000000,16.000000,18.000000,15.000000
mean,9.50000,2.850000,0.055556,25.950000,82.187500,0.277778,0.502667
std,5.91608,1.980829,0.235702,1.801111,10.765493,0.460889,0.209061
min,0.00000,0.000000,0.000000,22.400000,68.000000,0.000000,0.140000
25%,4.75000,1.000000,0.000000,24.600000,74.500000,0.000000,0.350000
50%,9.50000,3.000000,0.000000,26.500000,77.500000,0.000000,0.540000
75%,14.25000,4.250000,0.000000,27.025000,90.750000,0.750000,0.665000
max,19.00000,6.000000,1.000000,28.600000,99.000000,1.000000,0.810000

In [5]:
df.head()

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.1,99.0,0.0,rainy,0.14
1,1,08-02,1,0.0,26.4,NaN,0.0,sunny,NaN
2,2,08-03,2,0.0,NaN,96.0,0.0,rainy,0.21
3,3,08-04,3,0.0,24.1,68.0,0.0,overcast,0.68
4,4,08-05,4,NaN,24.7,98.0,0.0,rainy,0.20

In [6]:
df_clean = df[df.isnull().sum(axis=1) < 4].reset_index(drop=True).copy()

In [7]:
df_clean.head()

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.1,99.0,0.0,rainy,0.14
1,1,08-02,1,0.0,26.4,NaN,0.0,sunny,NaN
2,2,08-03,2,0.0,NaN,96.0,0.0,rainy,0.21
3,3,08-04,3,0.0,24.1,68.0,0.0,overcast,0.68
4,4,08-05,4,NaN,24.7,98.0,0.0,rainy,0.20

In [8]:
HmMean = df_clean["Humidity"].mean()
HdMode = df_clean["Holiday"].mode()[0]
df_clean["Humidity"] = df_clean["Humidity"].fillna(HmMean)
df_clean["Holiday"] = df_clean["Holiday"].fillna(HdMode)
df_clean.head()

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.1,99.0000,0.0,rainy,0.14
1,1,08-02,1,0.0,26.4,82.1875,0.0,sunny,NaN
2,2,08-03,2,0.0,NaN,96.0000,0.0,rainy,0.21
3,3,08-04,3,0.0,24.1,68.0000,0.0,overcast,0.68
4,4,08-05,4,0.0,24.7,98.0000,0.0,rainy,0.20

In [9]:
df_clean["Temp"] = df_clean["Temp"].interpolate(method="linear")
df_clean.head()

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.10,99.0000,0.0,rainy,0.14
1,1,08-02,1,0.0,26.40,82.1875,0.0,sunny,NaN
2,2,08-03,2,0.0,25.25,96.0000,0.0,rainy,0.21
3,3,08-04,3,0.0,24.10,68.0000,0.0,overcast,0.68
4,4,08-05,4,0.0,24.70,98.0000,0.0,rainy,0.20

In [10]:
df_clean

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.10,99.0000,0.0,rainy,0.14
1,1,08-02,1,0.0,26.40,82.1875,0.0,sunny,NaN
2,2,08-03,2,0.0,25.25,96.0000,0.0,rainy,0.21
3,3,08-04,3,0.0,24.10,68.0000,0.0,overcast,0.68
4,4,08-05,4,0.0,24.70,98.0000,0.0,rainy,0.20
5,5,08-06,5,0.0,26.50,98.0000,0.0,NaN,0.32
6,6,08-07,6,0.0,27.60,78.0000,0.0,rainy,0.72
7,7,08-08,0,0.0,28.20,82.1875,0.0,rainy,0.61
8,8,08-09,1,0.0,27.10,70.0000,0.0,overcast,NaN
9,9,08-10,2,1.0,26.70,75.0000,NaN,sunny,0.54
10,11,08-12,4,0.0,24.30,77.0000,0.0,overcast,0.67
11,12,08-13,5,0.0,23.10,77.0000,1.0,sunny,0.66
12,13,08-14,6,0.0,22.40,89.0000,1.0,rainy,0.38
13,14,08-15,0,0.0,24.45,80.0000,1.0,sunny,0.46
14,15,08-16,1,0.0,26.50,88.0000,1.0,rainy,NaN
15,16,08-17,2,0.0,28.60,76.0000,0.0,NaN,0.52
16,18,08-19,4,0.0,27.00,73.0000,1.0,overcast,0.62
17,19,08-20,5,0.0,26.90,73.0000,0.0,sunny,0.81

In [12]:
df_clean["Outlook"] = df_clean["Outlook"].ffill()
df_clean.head()

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.10,99.0000,0.0,rainy,0.14
1,1,08-02,1,0.0,26.40,82.1875,0.0,sunny,NaN
2,2,08-03,2,0.0,25.25,96.0000,0.0,rainy,0.21
3,3,08-04,3,0.0,24.10,68.0000,0.0,overcast,0.68
4,4,08-05,4,0.0,24.70,98.0000,0.0,rainy,0.20

In [13]:
df_clean

,Unnamed: 0,Date,Weekday,Holiday,Temp,Humidity,Wind,Outlook,Crowdedness
0,0,08-01,0,0.0,25.10,99.0000,0.0,rainy,0.14
1,1,08-02,1,0.0,26.40,82.1875,0.0,sunny,NaN
2,2,08-03,2,0.0,25.25,96.0000,0.0,rainy,0.21
3,3,08-04,3,0.0,24.10,68.0000,0.0,overcast,0.68
4,4,08-05,4,0.0,24.70,98.0000,0.0,rainy,0.20
5,5,08-06,5,0.0,26.50,98.0000,0.0,rainy,0.32
6,6,08-07,6,0.0,27.60,78.0000,0.0,rainy,0.72
7,7,08-08,0,0.0,28.20,82.1875,0.0,rainy,0.61
8,8,08-09,1,0.0,27.10,70.0000,0.0,overcast,NaN
9,9,08-10,2,1.0,26.70,75.0000,NaN,sunny,0.54
10,11,08-12,4,0.0,24.30,77.0000,0.0,overcast,0.67
11,12,08-13,5,0.0,23.10,77.0000,1.0,sunny,0.66
12,13,08-14,6,0.0,22.40,89.0000,1.0,rainy,0.38
13,14,08-15,0,0.0,24.45,80.0000,1.0,sunny,0.46
14,15,08-16,1,0.0,26.50,88.0000,1.0,rainy,NaN
15,16,08-17,2,0.0,28.60,76.0000,0.0,rainy,0.52
16,18,08-19,4,0.0,27.00,73.0000,1.0,overcast,0.62
17,19,08-20,5,0.0,26.90,73.0000,0.0,sunny,0.81

In [14]:
df_clean2 = df_clean.copy()

In [15]:
df_clean2["Outlook"].value_counts()

Outlook
rainy       9
sunny       5
overcast    4
Name: count, dtype: int64