In [1]:
print("Hello")

Hello

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("./emp.csv")
df

df2 = df.copy()

df.columns


sorted(df2["job"].unique())


df2["job"].value_counts()


# Label Encoding (Custom Mapping)
cols_nums = {"job": {"ANALYST": 3, "CLERK": 5, "MANAGER": 2, "PRESIDENT": 1, "SALESMAN": 4}}

df2 = df2.replace(cols_nums)

df2.head()

def salCatg(salary):
    if salary >= 3000:
        r = 1
    elif salary >= 1500:
        r = 2
    else:
        r = 3
    return r


# Binning (for Salary)
df2["sal"] = df2["sal"].apply(salCatg)
df2.head()

# Automatic Label Encoding using Pandas (category + cat.codes)
df3 = df[df.columns]
df3.dtypes

df3["job"] = df3["job"].astype("category")
df3.dtypes

sorted(df3["job"].unique())

df3["job1"] = df3["job"].cat.codes
df3.head(len(df3))


df3["comm1"] = df3["comm"].astype("category")
df3.dtypes




df3["comm1"] = df3["comm1"].cat.codes
df3.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,job1,comm1
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,3,-1
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,2,-1
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,2,-1
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,2,-1
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,4,3

In [3]:
df3["cBE_Code"] = np.where(df3["hiredate"].str.contains("2001"), 1, 0)

In [4]:
df3

,empno,ename,job,mgr,hiredate,sal,comm,deptno,job1,comm1,cBE_Code
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,3,-1,1
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,2,-1,1
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,2,-1,1
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,2,-1,1
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,4,3,1
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,30,4,1,1
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,30,4,0,1
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,30,1,-1,1
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,30,4,2,1
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,20,0,-1,1
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,20,1,-1,0
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,20,0,-1,0
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,20,1,-1,0
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,10,1,-1,0

### Ordinal Encoder

In [5]:
from sklearn.preprocessing import OrdinalEncoder

In [6]:
sorted(df3["deptno"].unique())

[np.int64(10), np.int64(20), np.int64(30)]

In [11]:
ord_enc = OrdinalEncoder()
df3["dno_code"] = ord_enc.fit_transform(df3[["deptno"]])
df3[["ename", "deptno", "dno_code"]].head(14)

     ename  deptno  dno_code
0     KING      10       0.0
1    BLAKE      30       2.0
2    CLARK      10       0.0
3    JONES      20       1.0
4   MARTIN      30       2.0
5    ALLEN      30       2.0
6   TURNER      30       2.0
7    JAMES      30       2.0
8     WARD      30       2.0
9     FORD      20       1.0
10   SMITH      20       1.0
11   SCOTT      20       1.0
12   ADAMS      20       1.0
13  MILLER      10       0.0

### One Hot Encoder (Dummy) encoding

In [12]:
df4 = df.copy()

In [13]:
sorted(df4["deptno"].unique())

[np.int64(10), np.int64(20), np.int64(30)]

In [14]:
df4["depID"] = df4.deptno
df4

    empno   ename        job     mgr    hiredate   sal    comm  deptno  depID
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10     10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30     30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10     10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20     20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30     30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30     30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30     30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30     30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30     30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20     20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20     20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20     20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20     20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10     10

### One Hot Encoder

In [8]:
import category_encoders as ce

In [9]:
df5 = df.copy()

In [10]:
encoder = ce.OneHotEncoder(cols="deptno", use_cat_names=True)
df5["deptID"] = df5.deptno
data_encoded = encoder.fit_transform(df5)
data_encoded

,empno,ename,job,mgr,hiredate,sal,comm,deptno_10.0,deptno_30.0,deptno_20.0,deptID
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,1,0,0,10
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,0,1,0,30
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,1,0,0,10
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,0,0,1,20
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,0,1,0,30
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,0,1,0,30
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,0,1,0,30
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,0,1,0,30
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,0,1,0,30
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,0,0,1,20
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,0,0,1,20
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,0,0,1,20
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,0,0,1,20
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,1,0,0,10