In [19]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [20]:
df = pd.read_csv("./PlayGolfData.csv")
df

    Unnamed: 0   Date Weekday Month  ... Humidity Wind   Outlook Crowdedness
0            0  03-25     Mon   Mar  ...      Dry   No     sunny          85
1            1  03-26     Tue   Mar  ...    Humid  Yes     rainy          30
2            2  03-27     Wed   Mar  ...      Dry  Yes  overcast          65
3            3  03-28     Thu   Mar  ...      Dry  Yes     sunny          45
4            4  03-29     Fri   Mar  ...    Humid   No     rainy          25
5            5  03-30     Sat   Mar  ...    Humid   No  overcast          90
6            6  03-31     Sun   Mar  ...      Dry  Yes     sunny          95
7            7  04-01     Mon   Apr  ...    Humid   No     rainy          35
8            8  04-02     Tue   Apr  ...      Dry  Yes     sunny          70
9            9  04-03     Wed   Apr  ...      Dry  Yes  overcast          50
10          10  04-04     Thu   Apr  ...    Humid   No     sunny          80
11          11  04-05     Fri   Apr  ...      Dry  Yes     rainy          45

[12 rows x 9 columns]

### 1. Label Encoding

In [21]:
df_enc = df.copy()

le = LabelEncoder()

df_enc["Outlook"] = le.fit_transform(df_enc["Outlook"])
df_enc["Temperature"] = le.fit_transform(df_enc["Temperature"])

df_enc.head()

   Unnamed: 0   Date Weekday Month  ...  Humidity Wind Outlook  Crowdedness
0           0  03-25     Mon   Mar  ...       Dry   No       2           85
1           1  03-26     Tue   Mar  ...     Humid  Yes       1           30
2           2  03-27     Wed   Mar  ...       Dry  Yes       0           65
3           3  03-28     Thu   Mar  ...       Dry  Yes       2           45
4           4  03-29     Fri   Mar  ...     Humid   No       1           25

[5 rows x 9 columns]

### 2. Ordinal Encoding

In [22]:
ord_enc = OrdinalEncoder(categories=[
    ["Dry", "Humid"],
    ["No", "Yes"]
])

df_enc[["Humidity", "Wind"]] = ord_enc.fit_transform(
    df_enc[["Humidity", "Wind"]]
)

df_enc.head()

   Unnamed: 0   Date Weekday Month  ...  Humidity  Wind  Outlook  Crowdedness
0           0  03-25     Mon   Mar  ...       0.0   0.0        2           85
1           1  03-26     Tue   Mar  ...       1.0   1.0        1           30
2           2  03-27     Wed   Mar  ...       0.0   1.0        0           65
3           3  03-28     Thu   Mar  ...       0.0   1.0        2           45
4           4  03-29     Fri   Mar  ...       1.0   0.0        1           25

[5 rows x 9 columns]

### 3. One-Hot Encoding (Sklearn)

In [23]:
ohe = OneHotEncoder(sparse_output=False)

df_ohe = df_enc.copy()

encoded = ohe.fit_transform(df[["Month"]])
df_ohe = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(["Month"]))

df_ohe

    Month_Apr  Month_Mar
0         0.0        1.0
1         0.0        1.0
2         0.0        1.0
3         0.0        1.0
4         0.0        1.0
5         0.0        1.0
6         0.0        1.0
7         1.0        0.0
8         1.0        0.0
9         1.0        0.0
10        1.0        0.0
11        1.0        0.0

In [ ]:
ohe = OneHotEncoder(sparse_output=False)

df_enc["Month"] = ohe.fit_transform(df_enc[["Month"]])

df_enc

    Unnamed: 0   Date Weekday  Month  ...  Humidity  Wind  Outlook  Crowdedness
0            0  03-25     Mon    0.0  ...       0.0   0.0        2           85
1            1  03-26     Tue    0.0  ...       1.0   1.0        1           30
2            2  03-27     Wed    0.0  ...       0.0   1.0        0           65
3            3  03-28     Thu    0.0  ...       0.0   1.0        2           45
4            4  03-29     Fri    0.0  ...       1.0   0.0        1           25
5            5  03-30     Sat    0.0  ...       1.0   0.0        0           90
6            6  03-31     Sun    0.0  ...       0.0   1.0        2           95
7            7  04-01     Mon    1.0  ...       1.0   0.0        1           35
8            8  04-02     Tue    1.0  ...       0.0   1.0        2           70
9            9  04-03     Wed    1.0  ...       0.0   1.0        0           50
10          10  04-04     Thu    1.0  ...       1.0   0.0        2           80
11          11  04-05     Fri    1.0  ...       0.0   1.0        1           45

[12 rows x 9 columns]

### 4. One-Hot Encoding (Pandas Dummy)

In [25]:
df_enc = pd.get_dummies(df_enc, columns=["Temperature"])
df_enc

    Unnamed: 0   Date Weekday  ...  Temperature_0  Temperature_1  Temperature_2
0            0  03-25     Mon  ...          False           True          False
1            1  03-26     Tue  ...          False          False           True
2            2  03-27     Wed  ...          False           True          False
3            3  03-28     Thu  ...           True          False          False
4            4  03-29     Fri  ...          False          False           True
5            5  03-30     Sat  ...          False           True          False
6            6  03-31     Sun  ...          False           True          False
7            7  04-01     Mon  ...          False          False           True
8            8  04-02     Tue  ...          False           True          False
9            9  04-03     Wed  ...           True          False          False
10          10  04-04     Thu  ...          False           True          False
11          11  04-05     Fri  ...          False          False           True

[12 rows x 11 columns]

### 5. Custom Binary Encoding

In [26]:
cols_nums = {"Weekday": {"Mon": 1, "Tue": 2, "Wed": 3, "Thu": 4, "Fri": 5, "Sat": 6, "Sun": 7}}

df_enc = df_enc.replace(cols_nums)

df_enc

    Unnamed: 0   Date Weekday  ...  Temperature_0  Temperature_1  Temperature_2
0            0  03-25       1  ...          False           True          False
1            1  03-26       2  ...          False          False           True
2            2  03-27       3  ...          False           True          False
3            3  03-28       4  ...           True          False          False
4            4  03-29       5  ...          False          False           True
5            5  03-30       6  ...          False           True          False
6            6  03-31       7  ...          False           True          False
7            7  04-01       1  ...          False          False           True
8            8  04-02       2  ...          False           True          False
9            9  04-03       3  ...           True          False          False
10          10  04-04       4  ...          False           True          False
11          11  04-05       5  ...          False          False           True

[12 rows x 11 columns]

### 6. Target Encoding

In [27]:
df_te = df_enc.copy()

target_mean = df_te.groupby("Outlook")["Crowdedness"].mean()

df_te["Outlook_te"] = df_te["Outlook"].map(target_mean)
df_te.head()

   Unnamed: 0   Date Weekday  ...  Temperature_1  Temperature_2  Outlook_te
0           0  03-25       1  ...           True          False   75.000000
1           1  03-26       2  ...          False           True   33.750000
2           2  03-27       3  ...           True          False   68.333333
3           3  03-28       4  ...          False          False   75.000000
4           4  03-29       5  ...          False           True   33.750000

[5 rows x 12 columns]

### 7. Custom Function Encoding

In [29]:
def temp_encoding(val):
    if val == "Low":
        return 1
    elif val == "High":
        return 2
    else:
        return 3

df_cf = df.copy()
df_cf["Temp_encoded"] = df_cf["Temperature"].apply(temp_encoding)
df_cf.head()

   Unnamed: 0   Date Weekday Month  ... Wind   Outlook Crowdedness Temp_encoded
0           0  03-25     Mon   Mar  ...   No     sunny          85            2
1           1  03-26     Tue   Mar  ...  Yes     rainy          30            1
2           2  03-27     Wed   Mar  ...  Yes  overcast          65            2
3           3  03-28     Thu   Mar  ...  Yes     sunny          45            3
4           4  03-29     Fri   Mar  ...   No     rainy          25            1

[5 rows x 10 columns]

### 8. Frequency Encoding

In [30]:
freq = df["Outlook"].value_counts()

df_freq = df.copy()
df_freq["Outlook_freq"] = df_freq["Outlook"].map(freq)
df_freq.head()

   Unnamed: 0   Date Weekday Month  ... Wind   Outlook Crowdedness Outlook_freq
0           0  03-25     Mon   Mar  ...   No     sunny          85            5
1           1  03-26     Tue   Mar  ...  Yes     rainy          30            4
2           2  03-27     Wed   Mar  ...  Yes  overcast          65            3
3           3  03-28     Thu   Mar  ...  Yes     sunny          45            5
4           4  03-29     Fri   Mar  ...   No     rainy          25            4

[5 rows x 10 columns]

### 9. Binary Encoding (Library-style idea)

In [31]:
df_be = df.copy()
df_be["Outlook_code"] = df_be["Outlook"].astype("category").cat.codes
df_be["Outlook_bin"] = df_be["Outlook_code"].apply(lambda x: format(x, '03b'))
df_be.head()

   Unnamed: 0   Date Weekday  ... Crowdedness Outlook_code Outlook_bin
0           0  03-25     Mon  ...          85            2         010
1           1  03-26     Tue  ...          30            1         001
2           2  03-27     Wed  ...          65            0         000
3           3  03-28     Thu  ...          45            2         010
4           4  03-29     Fri  ...          25            1         001

[5 rows x 11 columns]