In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
import seaborn as sns

In [2]:
df = pd.read_csv("../../DataSets/SalesRecords.csv")

In [10]:
df1 = df.groupby("Region")["Units Sold"].sum().reset_index()
df1

                              Region  Units Sold
0                               Asia       59967
1              Australia and Oceania       68325
2  Central America and the Caribbean       35771
3                             Europe       98117
4       Middle East and North Africa       48678
5                      North America       19143
6                 Sub-Saharan Africa      182870

In [11]:
total_units = df1["Units Sold"].sum() # Calculating the total units sold acrosss all regions

total_units

df1["Percentage"] = (df1["Units Sold"]  / total_units) * 100

df1

                              Region  Units Sold  Percentage
0                               Asia       59967   11.692414
1              Australia and Oceania       68325   13.322063
2  Central America and the Caribbean       35771    6.974658
3                             Europe       98117   19.130932
4       Middle East and North Africa       48678    9.491276
5                      North America       19143    3.732518
6                 Sub-Saharan Africa      182870   35.656140

In [12]:
import math
import squarify

In [14]:
# Create a Seaborn/Matplotlib color palette
pal_vi = sns.color_palette("viridis", len(df1))

In [15]:
def get_color(name, number):
    pal = list(sns.color_palette(palette=name, n_colors=number).as_hex())
    return pal

In [16]:
pal_vi = get_color("viridis_r", len(df1))
pal_plas = get_color("plasma_r", len(df1))
pal_spec = get_color("Spectral", len(df1))
pal_hsv = get_color("hsv", len(df1))

In [17]:
# Create a single figure with a 2x2 grid of subplot
colNm1 = "Region"
colNm2 = "Units Sold"
col1 = df[colNm1]
col2 = df[colNm2]

In [18]:
import matplotlib.pyplot as plt

In [ ]:
# 1. Barplot
fig, ax = plt.subplot(figsize=(5, 5))
ax = sns.barplot(data=df1, x=colNm1, y=colNm2, hue=colNm1, errorbar=None, palette=pal_plas)
ax.set_facecolor("#00FFFF")

# Rotate x-ticks
plt.xticks(rotation=45, ha="right")
# Add labels on top of each bar
for index, row in df1.iterrows():
    formatted_value = f"{row[colNm2]:},.0f"
    ax.text(index, row[colNm2] + 50,
            formatted_value, color="blue", ha="center")