In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing  import LabelEncoder, OneHotEncoder

pd.set_option("display.max_column", None)

### Task 1

In [3]:
train_data = pd.read_csv("../../DataSets/house_price_classification.csv")
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,2

In [4]:
train_data.shape

(1460, 83)

In [5]:
train_data.drop(["PriceCategory", "SalePrice"], axis=1)
train_data = train_data.drop(["PoolQC", "MiscFeature"], axis=1)

In [6]:
train_cols = train_data.columns

missing_train_cols = []
missing_train_val = []
for col in train_cols:
    if train_data[col].isnull().sum() > 0:
        missing_train_cols.append(col)
        missing_train_val.append(train_data[col].isnull().sum())
        print(f"column {col} have {train_data[col].isnull().sum()} missing values.")

column LotFrontage have 259 missing values.
column Alley have 1369 missing values.
column MasVnrType have 872 missing values.
column MasVnrArea have 8 missing values.
column BsmtQual have 37 missing values.
column BsmtCond have 37 missing values.
column BsmtExposure have 38 missing values.
column BsmtFinType1 have 37 missing values.
column BsmtFinType2 have 38 missing values.
column Electrical have 1 missing values.
column FireplaceQu have 690 missing values.
column GarageType have 81 missing values.
column GarageYrBlt have 81 missing values.
column GarageFinish have 81 missing values.
column GarageQual have 81 missing values.
column GarageCond have 81 missing values.
column Fence have 1179 missing values.

In [7]:
train_data["LotFrontage"] = train_data["LotFrontage"].fillna(train_data["LotFrontage"].median(), inplace=True)
train_data["MasVnrArea"] = train_data["MasVnrArea"].fillna(train_data["MasVnrArea"].median(), inplace=True)
train_data["GarageYrBlt"] = train_data["GarageYrBlt"].fillna(train_data["GarageYrBlt"].median(), inplace=True)

train_data["Electrical"] = train_data["Electrical"].fillna(train_data["Electrical"].mode()[0], inplace=True)

bsmt_cols = ["BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2"]
for col in bsmt_cols:
    train_data[col] = train_data[col].fillna("None", inplace=True)

garage_num_cols = ["GarageYrBlt"]
garage_cat_cols = ["GarageType", "GarageFinish", "GarageQual", "GarageCond"]

for col in garage_cat_cols:
    train_data[col] = train_data[col].fillna("None", inplace=True)

for col in garage_num_cols:
    train_data[col] = train_data[col].fillna(train_data[col].median(), inplace=True)

high_missing_cols = ["Alley", "FireplaceQu", "Fence"]
for col in high_missing_cols:
    train_data[col] = train_data[col].fillna("None", inplace=True)

train_data["MasVnrType"] = train_data["MasVnrType"].fillna("None", inplace=True)

print(train_data.isnull().sum().sort_values(ascending=False).head(10))

Unnamed: 0     0
Id             0
MSSubClass     0
MSZoning       0
LotFrontage    0
LotArea        0
Street         0
Alley          0
LotShape       0
LandContour    0
dtype: int64

C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data["LotFrontage"] = train_data["LotFrontage"].fillna(train_data["LotFrontage"].median(), inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data["MasVnrArea"] = train_data["MasVnrArea"].fillna(train_data["MasVnrArea"].median(), inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data["GarageYrBlt"] = train_data["GarageYrBlt"].fillna(train_data["GarageYrBlt"].median(), inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data["Electrical"] = train_data["Electrical"].fillna(train_data["Electrical"].mode()[0], inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data[col] = train_data[col].fillna("None", inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data[col] = train_data[col].fillna("None", inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:18: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data[col] = train_data[col].fillna(train_data[col].median(), inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:22: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data[col] = train_data[col].fillna("None", inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_7104\114524966.py:24: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_data["MasVnrType"] = train_data["MasVnrType"].fillna("None", inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import r2_score
import numpy as np

In [9]:
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,None,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,None,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,None,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,None,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,None,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,None,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,None,0,12,2008,WD,Normal,250000,2

In [10]:
train_data["MSZoning"].value_counts()

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

In [11]:
train_data["Street"].value_counts()

Street
Pave    1454
Grvl       6
Name: count, dtype: int64

In [12]:
# Make sure we’re working with the DataFrame
ohe = OneHotEncoder(sparse_output=False)

# Fit & transform, keep as a separate array
street_encoded = ohe.fit_transform(train_data[["Street"]])

# Convert to DataFrame
street_encoded_df = pd.DataFrame(
    street_encoded, 
    columns=ohe.get_feature_names_out(["Street"]),
    index=train_data.index  # keep the same row indices
)

# Concatenate with original DataFrame (drop old 'Street')
train_data = pd.concat([train_data.drop("Street", axis=1), street_encoded_df], axis=1)

In [13]:
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory,Street_Grvl,Street_Pave
0,0,1,60,RL,65.0,8450,None,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,None,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,None,0,2,2008,WD,Normal,208500,2,0.0,1.0
1,1,2,20,RL,80.0,9600,None,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,None,0,5,2007,WD,Normal,181500,1,0.0,1.0
2,2,3,60,RL,68.0,11250,None,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,None,0,9,2008,WD,Normal,223500,2,0.0,1.0
3,3,4,70,RL,60.0,9550,None,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,None,0,2,2006,WD,Abnorml,140000,1,0.0,1.0
4,4,5,60,RL,84.0,14260,None,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,None,0,12,2008,WD,Normal,250000,2,0.0,1.0

In [14]:
categorical_cols = train_data.select_dtypes(include=["object"]).columns

C:\Users\PC\AppData\Local\Temp\ipykernel_7104\480494598.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = train_data.select_dtypes(include=["object"]).columns

In [15]:
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    train_data[col] = le.fit_transform(train_data[col].astype(str))
    label_encoders[col] = le

In [16]:
train_data

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory,Street_Grvl,Street_Pave
0,0,1,60,3,65.0,8450,1,3,3,0,4,0,5,2,2,0,5,7,5,2003,2003,1,1,12,13,1,196.0,2,4,2,2,4,3,2,706,6,0,150,856,1,0,1,4,856,854,0,1710,1,0,2,1,3,1,2,8,6,0,3,1,2003.0,2,2,548,5,5,2,0,61,0,0,0,0,4,0,2,2008,8,4,208500,2,0.0,1.0
1,1,2,20,3,80.0,9600,1,3,3,0,2,0,24,1,2,0,2,6,8,1976,1976,1,1,8,8,2,0.0,3,4,1,2,4,1,0,978,6,0,284,1262,1,0,1,4,1262,0,0,1262,0,1,2,0,3,1,3,6,6,1,5,1,1976.0,2,2,460,5,5,2,298,0,0,0,0,0,4,0,5,2007,8,4,181500,1,0.0,1.0
2,2,3,60,3,68.0,11250,1,0,3,0,4,0,5,2,2,0,5,7,5,2001,2002,1,1,12,13,1,162.0,2,4,2,2,4,2,2,486,6,0,434,920,1,0,1,4,920,866,0,1786,1,0,2,1,3,1,2,6,6,1,5,1,2001.0,2,2,608,5,5,2,0,42,0,0,0,0,4,0,9,2008,8,4,223500,2,0.0,1.0
3,3,4,70,3,60.0,9550,1,0,3,0,0,0,6,2,2,0,5,7,5,1915,1970,1,1,13,15,2,0.0,3,4,0,4,1,3,0,216,6,0,540,756,1,2,1,4,961,756,0,1717,1,0,1,0,3,1,2,7,6,1,2,5,1998.0,3,3,642,5,5,2,0,35,272,0,0,0,4,0,2,2006,8,0,140000,1,0.0,1.0
4,4,5,60,3,84.0,14260,1,0,3,0,2,0,15,2,2,0,5,8,5,2000,2000,1,1,12,13,1,350.0,2,4,2,2,4,0,2,655,6,0,490,1145,1,0,1,4,1145,1053,0,2198,1,0,2,1,4,1,2,9,6,1,5,1,2000.0,2,3,836,5,5,2,192,84,0,0,0,0,4,0,12,2008,8,4,250000,2,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,1456,60,3,62.0,7917,1,3,3,0,4,0,8,2,2,0,5,6,5,1999,2000,1,1,12,13,2,0.0,3,4,2,2,4,3,6,0,6,0,953,953,1,0,1,4,953,694,0,1647,0,0,2,1,3,1,3,7,6,1,5,1,1999.0,2,2,460,5,5,2,0,40,0,0,0,0,4,0,8,2007,8,4,175000,1,0.0,1.0
1456,1456,1457,20,3,85.0,13175,1,3,3,0,4,0,14,2,2,0,2,6,6,1978,1988,1,1,9,10,3,119.0,3,4,1,2,4,3,0,790,5,163,589,1542,1,4,1,4,2073,0,0,2073,1,0,2,0,3,1,3,7,2,2,5,1,1978.0,3,2,500,5,5,2,349,0,0,0,0,0,2,0,2,2010,8,4,210000,2,0.0,1.0
1457,1457,1458,70,3,66.0,9042,1,3,3,0,4,0,6,2,2,0,5,7,9,1941,2006,1,1,5,5,2,0.0,0,2,4,4,1,3,2,275,6,0,877,1152,1,0,1,4,1188,1152,0,2340,0,0,2,0,4,1,2,9,6,2,2,1,1941.0,2,1,252,5,5,2,0,60,0,0,0,0,0,2500,5,2010,8,4,266500,2,0.0,1.0
1458,1458,1459,20,3,68.0,9717,1,3,3,0,4,0,12,2,2,0,2,5,6,1950,1996,3,1,8,8,2,0.0,3,4,1,4,4,2,2,49,5,1029,0,1078,1,2,1,0,1078,0,0,1078,1,0,1,0,2,1,2,5,6,0,3,1,1950.0,3,1,240,5,5,2,366,0,112,0,0,0,4,0,4,2010,8,4,142125,1,0.0,1.0
1459,1459,1460,20,3,75.0,9937,1,3,3,0,4,0,7,2,2,0,2,5,6,1965,1965,1,1,6,6,2,0.0,2,4,1,4,4,3,1,830,3,290,136,1256,1,2,1,4,1256,0,0,1256,1,0,1,1,3,1,3,6,6,0,3,1,1965.0,0,1,276,5,5,2,736,68,0,0,0,0,4,0,6,2008,8,4,147500,1,0.0,1.0

In [17]:
train_data.to_csv("../../DataSets/house_price_classification_cleaned.csv")

### Task 2

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
y = train_data["PriceCategory"]
X = train_data.drop(["Id", "PriceCategory"], axis=1)

In [20]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.3, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.25, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
X_train_70 = pd.concat((X_train1, y_train1), axis=1)
X_train_75 = pd.concat((X_train2, y_train2), axis=1)
X_train_80 = pd.concat((X_train3, y_train3), axis=1)

In [22]:
X_train_70.head()

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Street_Grvl,Street_Pave,PriceCategory
135,135,20,3,80.0,10400,1,3,3,0,4,0,14,2,2,0,2,7,6,1970,1970,3,1,9,10,1,288.0,3,4,2,4,4,3,6,0,6,0,1304,1304,1,2,1,4,1682,0,0,1682,0,0,2,0,3,1,3,7,6,1,2,1,1970.0,3,2,530,5,5,2,98,0,0,0,0,0,2,0,5,2008,8,4,174000,0.0,1.0,1
1452,1452,180,4,35.0,3675,1,3,3,0,4,0,7,2,2,4,7,5,5,2005,2005,1,1,12,13,1,80.0,3,4,2,2,4,1,2,547,6,0,0,547,1,2,1,4,1072,0,0,1072,1,0,1,0,2,1,3,5,6,0,3,2,2005.0,0,2,525,5,5,2,0,28,0,0,0,0,4,0,5,2006,8,4,145000,0.0,1.0,1
762,762,60,1,72.0,8640,1,3,3,0,4,0,21,2,2,0,5,7,5,2009,2009,1,1,12,13,2,0.0,3,4,2,2,4,2,2,24,6,0,732,756,1,0,1,4,764,783,0,1547,0,0,2,1,3,1,2,7,6,0,3,1,2009.0,3,2,614,5,5,2,169,45,0,0,0,0,4,0,6,2010,2,4,215200,0.0,1.0,2
932,932,20,3,84.0,11670,1,0,3,0,0,0,21,8,2,0,2,9,5,2006,2006,3,1,12,7,3,302.0,0,4,2,0,1,3,6,0,6,0,1905,1905,1,0,1,4,1905,0,0,1905,0,0,2,0,3,1,0,8,6,1,2,1,2006.0,0,3,788,5,5,2,0,191,0,0,0,0,4,0,3,2007,8,4,320000,0.0,1.0,2
435,435,60,3,43.0,10667,1,1,3,0,1,0,5,4,2,0,5,7,6,1996,1996,1,1,12,13,2,0.0,2,4,2,2,4,0,2,385,0,344,70,799,1,0,1,4,827,834,0,1661,1,0,2,1,3,1,2,6,6,1,5,1,1996.0,2,2,550,5,5,2,158,61,0,0,0,0,4,0,4,2009,5,4,212000,0.0,1.0,2

In [23]:
X_train_70.to_csv("../../DataSets/house_price_classification_clean_train_70.csv")
X_train_75.to_csv("../../DataSets/house_price_classification_clean_train_75.csv")
X_train_80.to_csv("../../DataSets/house_price_classification_clean_train_80.csv")

In [24]:
X_test_30 = pd.concat((X_test1, y_test1), axis=1)
X_test_25 = pd.concat((X_test2, y_test2), axis=1)
X_test_20 = pd.concat((X_test3, y_test3), axis=1)

In [25]:
X_test_30.to_csv("../../DataSets/house_price_classification_clean_test_30.csv")
X_test_25.to_csv("../../DataSets/house_price_classification_clean_test_25.csv")
X_test_20.to_csv("../../DataSets/house_price_classification_clean_test_20.csv")

### Task 3

### Part A: Decision Tree Algorithm

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np

In [28]:
X_train = pd.read_csv("../../DataSets/house_price_classification_clean_train_70.csv")
X_test = pd.read_csv("../../DataSets/house_price_classification_clean_test_30.csv")

In [29]:
X_train.shape

(1022, 82)

In [31]:
y_train = X_train["PriceCategory"]
y_test = X_test["PriceCategory"]

X_train = X_train.drop(["SalePrice", "PriceCategory"], axis=1)
X_test = X_test.drop(["SalePrice", "PriceCategory"], axis=1)

### Model 1 - Criterion: Entropy, max_dept: 4

In [32]:
dt1 = DecisionTreeClassifier(criterion="entropy", max_depth=4, random_state=42)
dt1.fit(X_train, y_train)
y_pred1 = dt1.predict(X_test)
accuracy1 = accuracy_score(y_test, y_pred1)

print(f"Accuracy of Decision Tree Classifier: {accuracy1:.4f}")
print(classification_report(y_test, y_pred1))

Accuracy of Decision Tree Classifier: 0.7740
              precision    recall  f1-score   support

           0       0.85      0.79      0.82       155
           1       0.70      0.60      0.65       141
           2       0.76      0.93      0.84       142

    accuracy                           0.77       438
   macro avg       0.77      0.77      0.77       438
weighted avg       0.77      0.77      0.77       438

### Model 2 - Criterion: Entropy, Max_dept: 5

In [33]:
dt2 = DecisionTreeClassifier(criterion="entropy", max_depth=5, random_state=42)
dt2.fit(X_train, y_train)
y_pred2 = dt2.predict(X_test)
accuracy2 = accuracy_score(y_test, y_pred2)

print(f"Accuracy of Decision Tree Classifier with max_depth=5: {accuracy2:.4f}")
print(classification_report(y_test, y_pred2))

Accuracy of Decision Tree Classifier with max_depth=5: 0.7808
              precision    recall  f1-score   support

           0       0.85      0.77      0.81       155
           1       0.66      0.72      0.69       141
           2       0.84      0.85      0.84       142

    accuracy                           0.78       438
   macro avg       0.78      0.78      0.78       438
weighted avg       0.79      0.78      0.78       438

### Model 3 --- Criterion: Gini, max_dept: 4

In [34]:
dt3 = DecisionTreeClassifier(criterion="gini", max_depth=4, random_state=42)
dt3.fit(X_train, y_train)
y_pred3 = dt3.predict(X_test)
accuracy3 = accuracy_score(y_test, y_pred3)

print(f"Accuracy of Decision Tree Classifier with Gini: {accuracy3:.4f}")
print(classification_report(y_test, y_pred3))

Accuracy of Decision Tree Classifier with Gini: 0.7580
              precision    recall  f1-score   support

           0       0.81      0.82      0.81       155
           1       0.67      0.59      0.63       141
           2       0.77      0.86      0.81       142

    accuracy                           0.76       438
   macro avg       0.75      0.76      0.75       438
weighted avg       0.75      0.76      0.75       438

### Model 3 --- Criterion: Gini, max_dept: 5

In [35]:
dt4 = DecisionTreeClassifier(criterion="gini", max_depth=5, random_state=42)
dt4.fit(X_train, y_train)
y_pred4 = dt4.predict(X_test)
accuracy4 = accuracy_score(y_test, y_pred4)

print(f"Accuracy of Decision Tree Classifier with Gini and max_depth=5: {accuracy4:.4f}")
print(classification_report(y_test, y_pred4))

Accuracy of Decision Tree Classifier with Gini and max_depth=5: 0.7763
              precision    recall  f1-score   support

           0       0.92      0.66      0.77       155
           1       0.62      0.83      0.71       141
           2       0.87      0.85      0.86       142

    accuracy                           0.78       438
   macro avg       0.80      0.78      0.78       438
weighted avg       0.81      0.78      0.78       438

In [36]:
from joblib import dump

In [44]:
def decision_tree_classifier(X_train, y_train, X_test, y_test, criterion="entropy", max_depth=4, file_name_suffix=None):
    dt = DecisionTreeClassifier(criterion=criterion, max_depth=max_depth, random_state=42)
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy of Decision Tree Classifier with '{criterion}' and max_depth={max_depth}: {accuracy:.4f}")
    print(classification_report(y_test, y_pred))

    # Saving the model
    file_name = f"./DT_{criterion}_max_depth_{max_depth}_{file_name_suffix}.joblib"
    dump(dt, file_name)

    return accuracy

In [45]:
dt_params = [
    {"criterion": "entropy", "max_depth": 4},
    {"criterion": "entropy", "max_depth": 5},
    {"criterion": "gini", "max_depth": 4},
    {"criterion": "gini", "max_depth": 5}
]

train_files = [
    "../../DataSets/house_price_classification_clean_train_70.csv",
    "../../DataSets/house_price_classification_clean_train_75.csv",
    "../../DataSets/house_price_classification_clean_train_80.csv"
]

test_files = [
    "../../DataSets/house_price_classification_clean_test_30.csv",
    "../../DataSets/house_price_classification_clean_test_25.csv",
    "../../DataSets/house_price_classification_clean_test_20.csv"
]

for train_file, test_file in zip(train_files, test_files):
    file_name_suffix = f"{train_file[-6:-4]}_{test_file[-6:-4]}"

    X_train = pd.read_csv(train_file)
    X_test = pd.read_csv(test_file)

    y_train = X_train["PriceCategory"]
    y_test = X_test["PriceCategory"]

    X_train = X_train.drop(["SalePrice", "PriceCategory"], axis=1)
    X_test = X_test.drop(["SalePrice", "PriceCategory"], axis=1)

    print(f"\n===== Evaluating on train file: {train_file[-6:-4]} and test file: {test_file[-6:-4]} =====\n")

    for params in dt_params:
        criterion = params["criterion"]
        max_depth = params["max_depth"]
        accuracy = decision_tree_classifier(X_train, y_train, X_test, y_test, criterion, max_depth, file_name_suffix)

===== Evaluating on train file: 70 and test file: 30 =====

Accuracy of Decision Tree Classifier with 'entropy' and max_depth=4: 0.7740
              precision    recall  f1-score   support

           0       0.85      0.79      0.82       155
           1       0.70      0.60      0.65       141
           2       0.76      0.93      0.84       142

    accuracy                           0.77       438
   macro avg       0.77      0.77      0.77       438
weighted avg       0.77      0.77      0.77       438

Accuracy of Decision Tree Classifier with 'entropy' and max_depth=5: 0.7808
              precision    recall  f1-score   support

           0       0.85      0.77      0.81       155
           1       0.66      0.72      0.69       141
           2       0.84      0.85      0.84       142

    accuracy                           0.78       438
   macro avg       0.78      0.78      0.78       438
weighted avg       0.79      0.78      0.78       438

Accuracy of Decision Tree Classifier with 'gini' and max_depth=4: 0.7580
              precision    recall  f1-score   support

           0       0.81      0.82      0.81       155
           1       0.67      0.59      0.63       141
           2       0.77      0.86      0.81       142

    accuracy                           0.76       438
   macro avg       0.75      0.76      0.75       438
weighted avg       0.75      0.76      0.75       438

Accuracy of Decision Tree Classifier with 'gini' and max_depth=5: 0.7763
              precision    recall  f1-score   support

           0       0.92      0.66      0.77       155
           1       0.62      0.83      0.71       141
           2       0.87      0.85      0.86       142

    accuracy                           0.78       438
   macro avg       0.80      0.78      0.78       438
weighted avg       0.81      0.78      0.78       438


===== Evaluating on train file: 75 and test file: 25 =====

Accuracy of Decision Tree Classifier with 'entropy' and max_depth=4: 0.7863
              precision    recall  f1-score   support

           0       0.83      0.80      0.82       132
           1       0.66      0.72      0.69       116
           2       0.87      0.84      0.85       117

    accuracy                           0.79       365
   macro avg       0.79      0.79      0.79       365
weighted avg       0.79      0.79      0.79       365

Accuracy of Decision Tree Classifier with 'entropy' and max_depth=5: 0.7808
              precision    recall  f1-score   support

           0       0.84      0.77      0.81       132
           1       0.66      0.72      0.69       116
           2       0.85      0.85      0.85       117

    accuracy                           0.78       365
   macro avg       0.78      0.78      0.78       365
weighted avg       0.79      0.78      0.78       365

Accuracy of Decision Tree Classifier with 'gini' and max_depth=4: 0.7781
              precision    recall  f1-score   support

           0       0.82      0.83      0.83       132
           1       0.64      0.73      0.68       116
           2       0.91      0.76      0.83       117

    accuracy                           0.78       365
   macro avg       0.79      0.78      0.78       365
weighted avg       0.79      0.78      0.78       365

Accuracy of Decision Tree Classifier with 'gini' and max_depth=5: 0.7781
              precision    recall  f1-score   support

           0       0.85      0.80      0.82       132
           1       0.65      0.74      0.69       116
           2       0.86      0.79      0.83       117

    accuracy                           0.78       365
   macro avg       0.78      0.78      0.78       365
weighted avg       0.79      0.78      0.78       365


===== Evaluating on train file: 80 and test file: 20 =====

Accuracy of Decision Tree Classifier with 'entropy' and max_depth=4: 0.7603
              precision    recall  f1-score   support

           0       0.78      0.79      0.78       110
           1       0.63      0.56      0.59        87
           2       0.84      0.91      0.87        95

    accuracy                           0.76       292
   macro avg       0.75      0.75      0.75       292
weighted avg       0.75      0.76      0.76       292

Accuracy of Decision Tree Classifier with 'entropy' and max_depth=5: 0.7671
              precision    recall  f1-score   support

           0       0.84      0.75      0.79       110
           1       0.59      0.76      0.66        87
           2       0.93      0.80      0.86        95

    accuracy                           0.77       292
   macro avg       0.78      0.77      0.77       292
weighted avg       0.79      0.77      0.77       292

Accuracy of Decision Tree Classifier with 'gini' and max_depth=4: 0.7500
              precision    recall  f1-score   support

           0       0.82      0.78      0.80       110
           1       0.61      0.60      0.60        87
           2       0.79      0.85      0.82        95

    accuracy                           0.75       292
   macro avg       0.74      0.74      0.74       292
weighted avg       0.75      0.75      0.75       292

Accuracy of Decision Tree Classifier with 'gini' and max_depth=5: 0.8048
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       110
           1       0.67      0.76      0.71        87
           2       0.89      0.82      0.85        95

    accuracy                           0.80       292
   macro avg       0.81      0.80      0.80       292
weighted avg       0.81      0.80      0.81       292